# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f3c40ca31f92c00f90f73821ea58344ff2967ca01f6d22620d848f0830f73a1872b1b57cb8e818ed65e24191bb30b920fe3ab2f3d55b012ee9eaf92d10fe66

test:
  secret_key_base: 8e3ab50e7fd5115a6ca88e76870c51b94a8fa6508307723688a02a89cb7ecf44e0578087e2c9703bec9e20b2b73a92f9b27bdf165fbea97de1aca395e4dda4bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
